package br.com.audacit.investimentos.database.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

@Data
@DynamoDBTable(tableName = "investimento")
public class InvestimentoEntity {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "codigo_movimentacao")
    private UUID codigoMovimentacao;

    @DynamoDBRangeKey(attributeName = "codigo_cliente")
    @DynamoDBIndexHashKey(attributeName = "codigo_cliente", globalSecondaryIndexName = "gsi_busca_cliente")
    private UUID codigoCliente;

    @DynamoDBIndexRangeKey(attributeName = "mes_movimentacao")
    private String mesMovimentacao;

    @DynamoDBAttribute(attributeName = "data_hora_movimentacao")
    @DynamoDBTypeConvertedTimestamp(pattern = "yyyy-MM-dd'T'HH:mm:ss'Z'", timeZone = "GMT-3")
    private LocalDateTime dataHoraMovimentacao;

    @DynamoDBAttribute(attributeName = "valor_movimentado")
    private BigDecimal valorMovimentado;

    @DynamoDBAttribute(attributeName = "saldo_cliente")
    private BigDecimal saldoCliente;

}
